# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15-browsers
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # checkout the repository
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: 
          name: install hugo
          command: | 
            wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
            sudo dpkg -i hugo_0.53_Linux-64bit.deb
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - deploy:
          name: deploy to GitHub Pages
          filters:
            branches:
              only: master
          command: |
            git clone $CIRCLE_REPOSITORY_URL out
            cd out
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cd ..
            hugo
            cp -a public/. out/.
            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cd out
            git config user.name "CircleCI"
            git config user.email "circle@circleci"
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]" --allow-empty
            git push origin gh-pages

