# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    filters:
      branches:
        not: gh-pages
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15-browsers
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # checkout the repository
      - checkout
      - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
      - sudo dpkg -i hugo_0.53_Linux-64bit.deb
      # install git submodules for managing third-party dependencies
      - run: git submodule update --init
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: deploy to GitHub Pages
          filters:
            branches:
              only: master
          command: |
            bash .circleci/deployToGithubPages.sh
